### ISSUE TITLE
erroneous use of Napi::HandleScope

### ISSUE THREAD

**Issue by mvduin** [amapili/weak-value-map#12]
It is unnecessary and pointless to create a Napi::HandleScope at the top-level of C++ functions/methods, since napi will already implicitly wrap the function call in one (at least that's what they imply with "The lifespan for the default scope is tied to the lifespan of the native method call. The result is that, by default, handles remain valid and the objects associated with these handles will be held live for the lifespan of the native method call.").

More importantly, using one in a function that returns a value is a bug since the lifetime of the returned value will end when your function returns, hence the value received by the caller is technically a dangling reference to garbage.

The main use of Napi::HandleScope is to avoid runaway memory usage when generating large amounts of garbage, e.g. temporaries created in a loop.  See [Object Lifetime Management](https://github.com/nodejs/node-addon-api/blob/master/doc/object_lifetime_management.md) in the node-addon-api docs for details.

**Comment by amapili** [comment]
Thanks for the info, fixed.
